# Generated by Django 5.1.5 on 2025-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursalesFarmacias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario',
            new_name='Stock',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sucursal_destino',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sucursal_origen',
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
