# Generated by Django 5.1.5 on 2025-01-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmaciasS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
