# Generated by Django 5.1.5 on 2025-01-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmaciasS', '0003_rename_fecha_pedido_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='inventarios',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=15),
        ),
    ]
