# Generated by Django 5.1.5 on 2025-01-28 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmaciasS', '0006_remove_entrega_sucursal_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
